# localization.py

# База данных локализации игры
LANG_DATA = {
    "RU": {
        "menu_title": "               THE VOIDER DOS SYSTEM                ",
        "menu_build": " Сборка",
        "menu_author": "Автор",
        "m_launch": "  1. ЗАПУСТИТЬ СИМУЛЯЦИЮ ТЕРМИНАЛА",
        "m_help": "  2. СИСТЕМНАЯ СПРАВКА (СПИСОК КОМАНД)",
        "m_intro": "  3. ЧТО К ЧЕМУ? (ВВЕДЕНИЕ ДЛЯ НОВИЧКА)",
        "m_lang": "  0. СМЕНИТЬ ЯЗЫК / CHANGE LANGUAGE [RU]",
        "m_exit": "  4. АВАРИЙНЫЙ ВЫХОД",
        "m_prompt": "\nВыбирете сектор загрузки > ",
        "m_exit_msg": "\nОтключение питания terminal. Система мертва...",
        
        # Справка (Help)
        "h_title": "=== ИНФОРМАЦИОННЫЙ БУФЕР (КОМАНДЫ) ===",
        "h_welcome": "Вы подключились к терминалу VOIDER-DOS.\n",
        "h_avail": "Доступные сейчас команды в режиме терминала:",
        "h_dir": "  dir       - Просмотр файлов и папок в текущей директории",
        "h_cd": "  cd <имя>  - Перейти внутрь выбранной папки",
        "h_cd2": "  cd ..     - Вернуться на один уровень назад (выше)",
        "h_type": "  type <ф>  - Прочесть текстовый файл (например: type note.txt)",
        "h_clear": "  clear     - Очистить экран от мусора",
        "h_exit": "  exit      - Бросить терминал и вернуться в главное меню\n",
        "h_warn": "=== ВНИМАНИЕ: СТОП-КРАН ===",
        "h_stop": "  В сочетании клавиш Ctrl+C зашит системный аварийный клапан.",
        "h_stop2": "  Используй это, если система сойдет с ума или будет взломана...",
        "h_back": "\nНажмите Enter для возврата в меню...",
        
        # Инструктаж (Intro)
        "i_title": "                 ИНСТРУКТАЖ ПО ВЫЖИВАНИЮ В ПУСТОТЕ (THE VOIDER)                 ",
        "i_p1": " Привет, оператор. Если ты никогда не видел текстовых игр — без паники.",
        "i_p2": " Перед тобой не просто черный экран, это {RED}VOIDER-DOS{WHITE} — симулятор старого терминала.",
        "i_p3": " Ты играешь за исследователя-тестировщика, который пробился в заброженную",
        "i_p4": " цифровую Пустоту. Твоя клавиатура — твое единственное оружие.",
        "i_task_t": " 📌 В ЧЕМ ТВОЯ ГЛАВНАЯ ЗАДАЧА?",
        "i_task_1": " Где-то в глубине сотен процедурно сгенерированных папок и секторов ",
        "i_task_2": " спрятаны {CYAN}3 ЧАСТИ ДНЕВНИКА НАБЛЮДАТЕЛЯ{WHITE}. Твоя цель — найти их все и выжить.",
        "i_task_3": " Но помни: мир создается заново при каждом запуске. Пути всегда разные.",
        "i_play_t": " 🕹️ ЧТО ДЕЛАТЬ И КАК ИГРАТЬ?",
        "i_play_1": " 1. После старта игры ты окажешься в корне системы {GREEN}VOID:\\>",
        "i_play_2": " 2. Вводи {GREEN}dir{WHITE} (или {GREEN}ls{WHITE}), чтобы увидеть, какие папки и файлы есть вокруг.",
        "i_play_3": " 3. Видишь папку? Пиши {GREEN}cd ИМЯ_ПАПКИ{WHITE}, чтобы зайти в нее. Иди глубже (до 4 уровней).",
        "i_play_4": " 4. Хочешь назад? Пиши {GREEN}cd ..{WHITE} — это поднимет тебя на уровень выше.",
        "i_play_5": " 5. Нашел файл? Пиши {GREEN}type ИМЯ_ФАЙЛА.txt{WHITE}, чтобы прочесть его. Там может быть лор!",
        "i_warn_t": " ⚠️ ЧТО ТУТ ДА КАК И ПОЧЕМУ? (ОПАСНОСТИ)",
        "i_warn_1": " Система нестабильна. Создатель Prunt оставил скрытые ловушки.",
        "i_warn_2": " * Если экран начнет безумно спамить символами — тебя взламывают.",
        "i_warn_3": " * Если ты провалишься на секретный уровень [-1] — пути назад не будет.",
        "i_warn_4": " В любой непонятной ситуации, или если игра пытается тебя сожрать,",
        "i_warn_5": " используй {RED}СТОП-КРАН (нажми сочетание клавиш Ctrl+C){WHITE}. Это твое спасение.",
        "i_back": "\nПрочитано. Нажми Enter, чтобы вернуться в главное меню и начать охоту..."
    },
    "EN": {
        "menu_title": "               THE VOIDER DOS SYSTEM                ",
        "menu_build": " Build",
        "menu_author": "Author",
        "m_launch": "  1. LAUNCH TERMINAL SIMULATION",
        "m_help": "  2. SYSTEM HELP (COMMAND LIST)",
        "m_intro": "  3. WHAT'S WHAT? (BEGINNER'S GUIDE)",
        "m_lang": "  0. СМЕНИТЬ ЯЗЫК / CHANGE LANGUAGE [EN]",
        "m_exit": "  4. EMERGENCY EXIT",
        "m_prompt": "\nSelect boot sector > ",
        "m_exit_msg": "\nPowering off terminal. The system is dead...",
        
        # Справка (Help)
        "h_title": "=== INFORMATION BUFFER (COMMANDS) ===",
        "h_welcome": "You have connected to the VOIDER-DOS terminal.\n",
        "h_avail": "Currently available commands in terminal mode:",
        "h_dir": "  dir       - View files and folders in the current directory",
        "h_cd": "  cd <name> - Move inside the selected folder",
        "h_cd2": "  cd ..     - Go back one level (upwards)",
        "h_type": "  type <f>  - Read a text file (e.g., type note.txt)",
        "h_clear": "  clear     - Clear the screen from clutter",
        "h_exit": "  exit      - Leave the terminal and return to main menu\n",
        "h_warn": "=== ATTENTION: BREAK VALVE ===",
        "h_stop": "  A system emergency valve is hardwired into the Ctrl+C shortcut.",
        "h_stop2": "  Use this if the system goes insane or gets compromised...",
        "h_back": "\nPress Enter to return to menu...",
        
        # Инструктаж (Intro)
        "i_title": "                 VOID SURVIVAL BRIEFING (THE VOIDER)                 ",
        "i_p1": " Hello, operator. If you've never played text games before — do not panic.",
        "i_p2": " This isn't just a black screen, this is {RED}VOIDER-DOS{WHITE} — an old terminal simulator.",
        "i_p3": " You play as a research tester who broke into the abandoned digital Void.",
        "i_p4": " Your keyboard is your only weapon.",
        "i_task_t": " 📌 WHAT IS YOUR MAIN OBJECTIVE?",
        "i_task_1": " Deep inside hundreds of procedurally generated folders and sectors, ",
        "i_task_2": " {CYAN}3 LOG PARTS OF THE OBSERVER{WHITE} are hidden. Your goal is to find them all and survive.",
        "i_task_3": " Remember: the world is rebuilt upon every launch. The paths are always changing.",
        "i_play_t": " 🕹️ WHAT TO DO & HOW TO PLAY?",
        "i_play_1": " 1. After launching the game, you will find yourself in the root: {GREEN}VOID:\\>",
        "i_play_2": " 2. Type {GREEN}dir{WHITE} (or {GREEN}ls{WHITE}) to see what folders and files are around you.",
        "i_play_3": " 3. See a folder? Type {GREEN}cd FOLDER_NAME{WHITE} to enter it. Go deeper (up to 4 levels).",
        "i_play_4": " 4. Want to go back? Type {GREEN}cd ..{WHITE} — this will bring you up one level.",
        "i_play_5": " 5. Found a file? Type {GREEN}type FILE_NAME.txt{WHITE} to read it. There might be lore inside!",
        "i_warn_t": " ⚠️ WHAT'S WHAT & WHY? (HAZARDS)",
        "i_warn_1": " The system is highly unstable. The creator, Prunt, left hidden traps.",
        "i_warn_2": " * If the screen starts spamming random characters — you are being hacked.",
        "i_warn_3": " * If you fall into secret level [-1] — there is no turning back.",
        "i_warn_4": " In any confusing situation, or if the game tries to consume you,",
        "i_warn_5": " use the {RED}EMERGENCY BRAKE (press Ctrl+C){WHITE}. This is your salvation.",
        "i_back": "\nRead. Press Enter to return to the main menu and begin the hunt..."
    }
}